# Generated by Django 2.1.2 on 2018-10-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_first_name', models.CharField(max_length=200)),
                ('alumni_last_name', models.CharField(max_length=200)),
                ('alumni_major', models.CharField(max_length=30)),
                ('alumni_grad', models.CharField(max_length=4)),
                ('alumni_school_id', models.CharField(max_length=15)),
                ('alumni_personal_email', models.EmailField(max_length=254)),
                ('alumni_school_email', models.EmailField(max_length=254)),
                ('alumni_approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=200)),
                ('business_address_one', models.CharField(max_length=200)),
                ('business_address_two', models.CharField(max_length=200)),
                ('business_city', models.CharField(max_length=200)),
                ('business_state', models.CharField(max_length=2)),
                ('business_zip', models.CharField(max_length=5)),
                ('business_desc', models.TextField()),
                ('business_phone', models.CharField(max_length=10)),
                ('business_end_date', models.DateField()),
                ('business_website', models.URLField()),
                ('business_num_visit', models.PositiveIntegerField()),
                ('business_approved', models.BooleanField()),
                ('business_alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Alumni')),
            ],
        ),
    ]
