# Generated by Django 2.1.2 on 2018-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20181028_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_address_two',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_website',
            field=models.URLField(blank=True),
        ),
    ]
