# Generated by Django 2.1.2 on 2018-11-18 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20181118_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_edit_date',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_submit_date',
        ),
        migrations.AddField(
            model_name='business',
            name='business_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
