# Generated by Django 2.1.2 on 2018-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20181118_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_edit_address_two',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=200), max_length=200),
        ),
    ]
